language: php
dist: xenial
php:
  - 7.2
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo
services:
  - docker
addons:
  - mariadb: '10.0'
before_install:
  - pwd
  - composer install
  - git clone https://github.com/backdrop/backdrop web
  - git clone https://github.com/drush-ops/drush web/drush
  - cd web/drush && git checkout 8.x && composer install
  - cp -a $HOME/backdrop-contrib/drush $HOME/web/drush/commands/backdrop

script:
  # Check code standards
  - vendor/bin/phpcs -n --standard=vendor/backdrop/coder/coder_sniffer/Backdrop --ignore="vendor/*,README.md" --extensions=install,module,php,inc,theme .

  # Unit tests

