language: php
dist: xenial
php:
  - 7.2
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/repo
services:
  - docker
before_install:
  - composer install
  - git clone git@github.com:backdrop/backdrop web
  - git clone git@github.com:drush-ops/drush web/drush
  - cd web/drush && git checkout 8.x && composer install
  - cp -a backdrop-contrib/drush web/drush/commands/backdrop

script:
  # Check code standards
  - vendor/bin/phpcs -n --standard=vendor/backdrop/coder/coder_sniffer/Backdrop --ignore="vendor/*,README.md" --extensions=install,module,php,inc,theme .

  # Unit tests

